const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const elements=new Map(),events=new Map();let coarse=true;
function element(id){if(!elements.has(id)){const handlers={},classes=new Set();elements.set(id,{id,hidden:true,disabled:false,textContent:'',style:{values:{},setProperty(k,v){this.values[k]=v;}},classList:{toggle(k,v){if(v)classes.add(k);else classes.delete(k);},add(k){classes.add(k);},remove(k){classes.delete(k);},contains:k=>classes.has(k)},addEventListener(k,f){(handlers[k]??=[]).push(f);},emit(k,data={}){for(const f of handlers[k]||[])f({pointerId:1,clientX:68,clientY:68,preventDefault(){},...data});},focus(){},setAttribute(){},querySelector(){return element(id+'-child');},setPointerCapture(){},getBoundingClientRect(){return {left:0,top:0,width:136,height:136};}});}return elements.get(id);}
const document={body:element('body'),getElementById:element,querySelectorAll:()=>[],querySelector:()=>element('query'),addEventListener(k,f){events.set(k,f);},hidden:false};
const window={addEventListener(k,f){events.set('window-'+k,f);}};
const context={console,Math,Date,Map,Set,document,window,matchMedia:()=>({get matches(){return coarse;},addEventListener(){}}),performance:{now:()=>100},setTimeout(){},clearTimeout(){},setInterval(){},Phaser:{Scene:class{},Game:class{},AUTO:0,Scale:{FIT:0,CENTER_BOTH:0},Input:{Keyboard:{JustDown:()=>false}}}};
vm.createContext(context);
const source=name=>fs.readFileSync(path.resolve(__dirname,'../dist/'+name),'utf8');
vm.runInContext(source('game.js')+'\nglobalThis.TestArena=Arena;',context);
vm.runInContext(source('online.js').replace('net=new OnlineRoom();window.bubbleOnline={snapshot:()=>net.snapshot()};','globalThis.TestRoom=OnlineRoom;'),context);
const moves=[],bombs=[],sent=[];
function reset(){const a=new context.TestArena();a.phase='playing';a.players=[{id:0,alive:true,pendingBombUntil:0}];a.keys=Object.fromEntries(['UP','RIGHT','DOWN','LEFT','W','D','S','A','SPACE','ENTER'].map(k=>[k,{isDown:false}]));a.tryMove=(p,d)=>{moves.push(d);return true;};a.placeBomb=()=>{bombs.push('keyboard');return true;};a.requestTouchBomb=()=>{bombs.push('touch');return true;};context.testArena=a;vm.runInContext('arena=testArena;net=undefined;options.mode="solo";',context);element('exit-overlay').hidden=true;element('menu').hidden=true;return a;}
let a=reset();vm.runInContext(source('mobile-controls.js'),context);
const checks=[];function test(name,run){run();checks.push(name);}
test('Touch device shows joystick and mobile help; PC shows only keyboard help',()=>{vm.runInContext('syncControls()',context);assert.equal(element('touch-controls').hidden,false);assert.equal(element('keyboard-guide').hidden,true);coarse=false;vm.runInContext('syncControls()',context);assert.equal(element('touch-controls').hidden,true);assert.equal(element('keyboard-guide').hidden,false);coarse=true;vm.runInContext('syncControls()',context);});
test('Two fingers can hold movement and tap bomb without cancelling movement',()=>{a=reset();element('move-stick').emit('pointerdown',{pointerId:11,clientX:110});assert(a.touch.has('right'));element('touch-bomb').emit('pointerdown',{pointerId:22});assert.equal(bombs.at(-1),'touch');assert(a.touch.has('right'));element('touch-bomb').emit('pointerup',{pointerId:22});assert(a.touch.has('right'));element('move-stick').emit('pointerup',{pointerId:11});assert.equal(a.touch.size,0);});
test('Joystick ignores a second movement finger and stops on pointer cancellation',()=>{a=reset();element('move-stick').emit('pointerdown',{pointerId:1,clientX:110});element('move-stick').emit('pointerdown',{pointerId:2,clientX:20});assert(a.touch.has('right'));element('move-stick').emit('pointercancel',{pointerId:1});assert.equal(a.touch.size,0);assert.equal(element('stick-thumb').style.values['--stick-x'],'0px');});
test('Dragging through the dead zone stops; dragging up changes direction',()=>{a=reset();element('move-stick').emit('pointerdown',{clientX:110});element('move-stick').emit('pointermove',{clientX:68});assert.equal(a.touch.size,0);element('move-stick').emit('pointermove',{clientY:20});assert(a.touch.has('up'));document.hidden=true;events.get('visibilitychange')();assert.equal(a.touch.size,0);document.hidden=false;});
test('PC arrow movement and same-computer WASD remain keyboard controls',()=>{a=reset();coarse=false;a.keys.RIGHT.isDown=true;a.humanInput(a.players[0]);assert.equal(moves.at(-1),1);a.keys.RIGHT.isDown=false;a.keys.W.isDown=true;vm.runInContext('options.mode="duo"',context);a.humanInput(a.players[0]);assert.equal(moves.at(-1),0);coarse=true;});
test('Accidental return pauses solo without exiting; cancel resumes the same round',()=>{a=reset();element('back-menu').emit('click');assert.equal(a.phase,'paused');assert.equal(element('exit-overlay').hidden,false);assert.equal(element('menu').hidden,true);element('exit-cancel').emit('click');assert.equal(a.phase,'playing');assert.equal(element('exit-overlay').hidden,true);assert.equal(element('menu').hidden,true);});
test('Online return does not leave until explicit confirmation',()=>{a=reset();let leaves=0;context.testNet={active:true,isHost:false,localId:1,releaseInput(){},leave(){leaves++;this.active=false;}};vm.runInContext('net=testNet',context);element('back-menu').emit('click');assert.equal(leaves,0);assert.equal(a.phase,'playing');element('exit-cancel').emit('click');assert.equal(leaves,0);element('back-menu').emit('click');element('exit-confirm').emit('click');assert.equal(leaves,1);assert.equal(a.phase,'menu');});
test('Guest joystick release sends stop; bombing keeps held direction and buffers tap',()=>{a=reset();const room=Object.create(context.TestRoom.prototype);Object.assign(room,{active:true,isHost:false,matchStarted:true,lastDirection:-1,sequence:0,send(c,m){sent.push(m);}});context.testNet=room;vm.runInContext('net=testNet',context);element('move-stick').emit('pointerdown',{clientX:110});assert.equal(sent.at(-1).direction,1);element('touch-bomb').emit('pointerdown',{pointerId:22});assert.equal(sent.at(-1).direction,1);assert.equal(sent.at(-1).buffered,true);element('touch-bomb').emit('pointerup',{pointerId:22});element('move-stick').emit('pointerup');assert.equal(sent.at(-1).direction,-1);assert.equal(sent.at(-1).bomb,false);});
test('Host accepts a new joystick direction immediately after a stop packet',()=>{a=reset();const conn={peer:'guest'},room=Object.create(context.TestRoom.prototype);Object.assign(room,{connections:new Map([['guest',conn]]),members:[{peer:'host'},{peer:'guest'}],inputs:new Map(),matchStarted:true});a.players.push({id:1,alive:true});room.hostMessage(conn,{kind:'input',sequence:1,direction:-1,bomb:false});room.hostMessage(conn,{kind:'input',sequence:2,direction:1,bomb:false});assert.equal(room.inputs.get(1).direction,1);room.hostMessage(conn,{kind:'input',sequence:3,direction:1,bomb:true,buffered:true});assert.equal(bombs.at(-1),'touch');});
console.log(JSON.stringify({checks:checks.length,passed:checks.length,scope:'Actual mobile pointer handlers, return flow and network input methods with DOM/Phaser stubs; physical phone rendering remains separate.'}));
